Resolve VCSWP-19101 (Initial work for the verify signature request feature)
FreeClimbAPI/php-sdk pull request #27
Opened 2023-03-31 22:23 UTC by amahadaya

Closes VCSWP-19101

2023-03-31 22:31 UTC, ngarg-vail requested changes

2023-03-31 22:31 UTC, ngarg-vail commented on test/Util/RequestVerifierTest.php
> +        $this->requestVerifierObject = new RequestVerifier();
this->requestVerifier

2023-03-31 22:31 UTC, ngarg-vail commented on test/Util/SignatureInformationTest.php
> +        $this->signatureInformationObject = new SignatureInformation($requestHeader);
this->signatureInformation

2023-03-31 22:31 UTC, ngarg-vail commented on lib/Util/RequestVerifier.php
> +    function verifyRequestSignature(string $requestBody, string $requestHeader, string $signingSecret, int $tolerance)
default tolerance not used

2023-03-31 22:38 UTC, amahadaya commented on lib/Util/RequestVerifier.php
> +    function verifyRequestSignature(string $requestBody, string $requestHeader, string $signingSecret, int $tolerance)
Will edit this in latest commit

2023-03-31 22:38 UTC, amahadaya commented on test/Util/SignatureInformationTest.php
> +        $this->signatureInformationObject = new SignatureInformation($requestHeader);
Will edit this in latest commit

2023-03-31 22:38 UTC, amahadaya commented on test/Util/RequestVerifierTest.php
> +        $this->requestVerifierObject = new RequestVerifier();
Will edit this in latest commit

2023-04-04 20:09 UTC, ngarg-vail approved these changes

2023-04-04 21:33 UTC, merged